Update pylint.yml for explicit failing

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -23,4 +23,9 @@ jobs:
       run: |
         pylint_score=$(pylint **/*.py | tail -2 | grep -oP '[0-9\.]+/10' | head -1 | grep -oP '[0-9\.]+')
         echo "Pylint score was $pylint_score"
-        if (( $(echo "$pylint_score < 8" | bc -l) )); then exit 1; fi
+        if (( $(echo "$pylint_score < 8" | bc -l) )); then 
+          echo "Pylint score is less than 8, failing the task."
+          exit 1
+        else
+          echo "Pylint score is 8 or above, task passed."
+        fi
